-- Guard scheduler schema (squashed). Prior tables are dropped in Go when present (see migrate.go).

-- ---------------------------------------------------------------------------
-- Configuration
-- ---------------------------------------------------------------------------
CREATE TABLE cfg (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    key TEXT NOT NULL,
    new_cfg JSONB NOT NULL,
    request_id UUID NULL,
    actor TEXT NULL,
    PRIMARY KEY (ts, id)
) PARTITION BY RANGE (ts);

CREATE INDEX audit_key_idx ON audit (key);

CREATE TABLE schedule (
    ts_date DATE NOT NULL,
    plan JSONB NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_from_slot TEXT NULL,
    PRIMARY KEY (ts_date)
) PARTITION BY RANGE (ts_date);

CREATE INDEX schedule_applied_at_idx ON schedule (applied_at DESC);

-- ---------------------------------------------------------------------------
-- Users (Clerk RBAC)
-- ---------------------------------------------------------------------------
CREATE TABLE app_users (
    clerk_user_id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('admin', 'readonly')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    invited_by TEXT NULL REFERENCES app_users (clerk_user_id)
);

CREATE TABLE user_invites (
    id BIGSERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('admin', 'readonly')),
    invited_by TEXT NOT NULL REFERENCES app_users (clerk_user_id),
    clerk_invitation_id TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    accepted_at TIMESTAMPTZ NULL
);

CREATE INDEX user_invites_pending_email_idx ON user_invites (lower(email))
WHERE accepted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Soldier availability
-- ---------------------------------------------------------------------------
CREATE TABLE soldier_status_resolved (
    id BIGSERIAL PRIMARY KEY,
    soldier_id TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NULL,
    status TEXT NOT NULL,
    note TEXT NULL,
    actor TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_open BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT soldier_status_resolved_status_chk CHECK (
        status IN ('away', 'sick', 'training', 'other', 'outing')
    )
);

CREATE INDEX soldier_status_resolved_soldier_start_idx
    ON soldier_status_resolved (soldier_id, start_at);

CREATE UNIQUE INDEX soldier_status_resolved_one_open_per_soldier
    ON soldier_status_resolved (soldier_id)
    WHERE is_open = true;

CREATE TABLE soldier_status_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    soldier_id TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NULL,
    status TEXT NOT NULL,
    note TEXT NULL,
    actor TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    compacted_at TIMESTAMPTZ NULL,
    PRIMARY KEY (start_at, id),
    CONSTRAINT soldier_status_entry_status_chk CHECK (
        status IN ('away', 'sick', 'training', 'other', 'outing')
    )
) PARTITION BY RANGE (start_at);

CREATE INDEX soldier_status_entry_soldier_idx
    ON soldier_status_entry (soldier_id, start_at);

CREATE INDEX soldier_status_entry_uncompacted_idx
    ON soldier_status_entry (compacted_at)
    WHERE compacted_at IS NULL;

CREATE TABLE soldier_state_snapshot (
    as_of DATE PRIMARY KEY,
    compacted_through TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- ---------------------------------------------------------------------------
-- Partitioning (40-day blocks; retain at least 30 calendar days)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION guard_partition_anchor()
RETURNS date
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT '2000-01-01'::date $$;

CREATE OR REPLACE FUNCTION guard_partition_days()
RETURNS integer
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT 40 $$;

CREATE OR REPLACE FUNCTION guard_partition_block_start(p_day date)
RETURNS date
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT guard_partition_anchor()
        + (
            (p_day - guard_partition_anchor())
            / guard_partition_days()
        ) * guard_partition_days();
$$;

CREATE OR REPLACE FUNCTION guard_partition_block_end(p_block_start date)
RETURNS date
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT p_block_start + guard_partition_days() $$;

CREATE OR REPLACE FUNCTION guard_ensure_audit_block(p_block_start date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'audit_b' || to_char(p_block_start, 'YYYYMMDD');
    range_from timestamptz := p_block_start::timestamptz;
    range_to timestamptz := guard_partition_block_end(p_block_start)::timestamptz;
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF audit FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

CREATE OR REPLACE FUNCTION guard_ensure_schedule_block(p_block_start date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'schedule_b' || to_char(p_block_start, 'YYYYMMDD');
    range_from date := p_block_start;
    range_to date := guard_partition_block_end(p_block_start);
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF schedule FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

CREATE OR REPLACE FUNCTION guard_ensure_soldier_status_block(p_block_start date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'soldier_status_entry_b' || to_char(p_block_start, 'YYYYMMDD');
    range_from timestamptz := p_block_start::timestamptz;
    range_to timestamptz := guard_partition_block_end(p_block_start)::timestamptz;
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF soldier_status_entry FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

CREATE OR REPLACE FUNCTION guard_ensure_partitions(
    retention_days int DEFAULT 30,
    future_days int DEFAULT 7
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    oldest_keep date;
    last_needed date;
    block_start date;
    step int := guard_partition_days();
BEGIN
    IF retention_days < 1 THEN
        RAISE EXCEPTION 'retention_days must be >= 1';
    END IF;
    IF future_days < 0 THEN
        RAISE EXCEPTION 'future_days must be >= 0';
    END IF;

    oldest_keep := current_date - retention_days + 1;
    last_needed := current_date + future_days;
    block_start := guard_partition_block_start(oldest_keep);

    WHILE block_start <= guard_partition_block_start(last_needed) LOOP
        PERFORM guard_ensure_audit_block(block_start);
        PERFORM guard_ensure_schedule_block(block_start);
        PERFORM guard_ensure_soldier_status_block(block_start);
        block_start := block_start + step;
    END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION guard_drop_old_partitions(retention_days int DEFAULT 30)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    oldest_keep date;
    block_days int := guard_partition_days();
    r record;
    dropped int := 0;
    block_start date;
    block_end date;
    range_from timestamptz;
    range_to timestamptz;
    uncompacted bigint;
BEGIN
    IF retention_days < 1 THEN
        RAISE EXCEPTION 'retention_days must be >= 1';
    END IF;

    oldest_keep := current_date - retention_days + 1;

    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'audit'
          AND c.relname ~ '^audit_b[0-9]{8}$'
    LOOP
        block_start := to_date(substring(r.part_name from 'b([0-9]{8})$'), 'YYYYMMDD');
        block_end := block_start + block_days;
        IF block_end <= oldest_keep THEN
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'schedule'
          AND c.relname ~ '^schedule_b[0-9]{8}$'
    LOOP
        block_start := to_date(substring(r.part_name from 'b([0-9]{8})$'), 'YYYYMMDD');
        block_end := block_start + block_days;
        IF block_end <= oldest_keep THEN
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'soldier_status_entry'
          AND c.relname ~ '^soldier_status_entry_b[0-9]{8}$'
    LOOP
        block_start := to_date(substring(r.part_name from 'b([0-9]{8})$'), 'YYYYMMDD');
        block_end := block_start + block_days;
        IF block_end <= oldest_keep THEN
            range_from := block_start::timestamptz;
            range_to := guard_partition_block_end(block_start)::timestamptz;
            SELECT count(*) INTO uncompacted
            FROM soldier_status_entry
            WHERE compacted_at IS NULL
              AND start_at >= range_from
              AND start_at < range_to;
            IF uncompacted > 0 THEN
                CONTINUE;
            END IF;
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    RETURN dropped;
END;
$$;

CREATE OR REPLACE FUNCTION guard_retention_maintain(
    retention_days int DEFAULT 30,
    future_days int DEFAULT 7
)
RETURNS integer
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM guard_ensure_partitions(retention_days, future_days);
    RETURN guard_drop_old_partitions(retention_days);
END;
$$;

SELECT guard_retention_maintain(30, 7);

-- Optional: daily retention when pg_cron is enabled (Neon).
DO $cron$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron')
       AND NOT EXISTS (
           SELECT 1 FROM cron.job WHERE jobname = 'guard-retention-maintain'
       ) THEN
        PERFORM cron.schedule(
            'guard-retention-maintain',
            '15 3 * * *',
            $$SELECT guard_retention_maintain(30, 7)$$
        );
    END IF;
EXCEPTION
    WHEN undefined_table OR undefined_function THEN
        NULL;
END;
$cron$;
