-- Soldier availability: hot partitioned entries + permanent resolved intervals.

CREATE TABLE soldier_status_resolved (
    id BIGSERIAL PRIMARY KEY,
    soldier_id TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NULL,
    status TEXT NOT NULL,
    note TEXT NULL,
    actor TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_open BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT soldier_status_resolved_status_chk CHECK (
        status IN ('away', 'sick', 'training', 'other', 'outing')
    )
);

CREATE INDEX soldier_status_resolved_soldier_start_idx
    ON soldier_status_resolved (soldier_id, start_at);

CREATE UNIQUE INDEX soldier_status_resolved_one_open_per_soldier
    ON soldier_status_resolved (soldier_id)
    WHERE is_open = true;

CREATE TABLE soldier_status_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    soldier_id TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NULL,
    status TEXT NOT NULL,
    note TEXT NULL,
    actor TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    compacted_at TIMESTAMPTZ NULL,
    PRIMARY KEY (start_at, id),
    CONSTRAINT soldier_status_entry_status_chk CHECK (
        status IN ('away', 'sick', 'training', 'other', 'outing')
    )
) PARTITION BY RANGE (start_at);

CREATE INDEX soldier_status_entry_soldier_idx
    ON soldier_status_entry (soldier_id, start_at);

CREATE INDEX soldier_status_entry_uncompacted_idx
    ON soldier_status_entry (compacted_at)
    WHERE compacted_at IS NULL;

CREATE TABLE soldier_state_snapshot (
    as_of DATE PRIMARY KEY,
    compacted_through TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE OR REPLACE FUNCTION guard_ensure_soldier_status_block(p_block_start date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'soldier_status_entry_b' || to_char(p_block_start, 'YYYYMMDD');
    range_from timestamptz := p_block_start::timestamptz;
    range_to timestamptz := guard_partition_block_end(p_block_start)::timestamptz;
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF soldier_status_entry FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

-- Extend partition maintenance for soldier_status_entry.
CREATE OR REPLACE FUNCTION guard_ensure_partitions(
    retention_days int DEFAULT 30,
    future_days int DEFAULT 7
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    oldest_keep date;
    last_needed date;
    block_start date;
    step int := guard_partition_days();
BEGIN
    IF retention_days < 1 THEN
        RAISE EXCEPTION 'retention_days must be >= 1';
    END IF;
    IF future_days < 0 THEN
        RAISE EXCEPTION 'future_days must be >= 0';
    END IF;

    oldest_keep := current_date - retention_days + 1;
    last_needed := current_date + future_days;
    block_start := guard_partition_block_start(oldest_keep);

    WHILE block_start <= guard_partition_block_start(last_needed) LOOP
        PERFORM guard_ensure_audit_block(block_start);
        PERFORM guard_ensure_schedule_block(block_start);
        PERFORM guard_ensure_soldier_status_block(block_start);
        block_start := block_start + step;
    END LOOP;
END;
$$;
