-- Daily range partitions for audit (ts) and schedule (ts_date).
-- Retention: daily partitions; see 000005_retention_30_days.sql for keep/drop policy.
-- Run guard_retention_maintain(30, 7) daily (app startup + guardcli db retention).

-- ---------------------------------------------------------------------------
-- audit
-- ---------------------------------------------------------------------------
ALTER TABLE audit RENAME TO audit_unpartitioned;

CREATE TABLE audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    key TEXT NOT NULL,
    new_cfg JSONB NOT NULL,
    request_id UUID NULL,
    actor TEXT NULL,
    PRIMARY KEY (ts, id)
) PARTITION BY RANGE (ts);

CREATE INDEX IF NOT EXISTS audit_key_idx ON audit (key);

CREATE OR REPLACE FUNCTION guard_ensure_audit_partition(p_day date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'audit_' || to_char(p_day, 'YYYYMMDD');
    range_from timestamptz := p_day::timestamptz;
    range_to timestamptz := (p_day + 1)::timestamptz;
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF audit FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

DO $migrate_audit$
DECLARE
    min_day date;
    max_day date;
    d date;
BEGIN
    SELECT
        coalesce(min(ts::date), current_date),
        coalesce(max(ts::date), current_date)
    INTO min_day, max_day
    FROM audit_unpartitioned;

    d := min_day - 1;
    WHILE d <= max_day + 7 LOOP
        PERFORM guard_ensure_audit_partition(d);
        d := d + 1;
    END LOOP;

    INSERT INTO audit (id, ts, key, new_cfg, request_id, actor)
    SELECT id, ts, key, new_cfg, request_id, actor
    FROM audit_unpartitioned;
END;
$migrate_audit$;

DROP TABLE audit_unpartitioned;

-- ---------------------------------------------------------------------------
-- schedule
-- ---------------------------------------------------------------------------
ALTER TABLE schedule RENAME TO schedule_unpartitioned;

CREATE TABLE schedule (
    ts_date DATE NOT NULL,
    plan JSONB NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_from_slot TEXT NULL,
    PRIMARY KEY (ts_date)
) PARTITION BY RANGE (ts_date);

CREATE INDEX IF NOT EXISTS schedule_applied_at_idx ON schedule (applied_at DESC);

CREATE OR REPLACE FUNCTION guard_ensure_schedule_partition(p_day date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'schedule_' || to_char(p_day, 'YYYYMMDD');
    range_from date := p_day;
    range_to date := p_day + 1;
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF schedule FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

DO $migrate_schedule$
DECLARE
    min_day date;
    max_day date;
    d date;
BEGIN
    SELECT
        coalesce(min(ts_date), current_date),
        coalesce(max(ts_date), current_date)
    INTO min_day, max_day
    FROM schedule_unpartitioned;

    d := min_day - 1;
    WHILE d <= max_day + 7 LOOP
        PERFORM guard_ensure_schedule_partition(d);
        d := d + 1;
    END LOOP;

    INSERT INTO schedule (ts_date, plan, applied_at, applied_from_slot)
    SELECT ts_date, plan, applied_at, applied_from_slot
    FROM schedule_unpartitioned;
END;
$migrate_schedule$;

DROP TABLE schedule_unpartitioned;

-- ---------------------------------------------------------------------------
-- retention helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION guard_ensure_partitions(
    retention_days int DEFAULT 30,
    future_days int DEFAULT 7
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    d date;
    start_day date;
    end_day date;
BEGIN
    IF retention_days < 1 THEN
        RAISE EXCEPTION 'retention_days must be >= 1';
    END IF;
    IF future_days < 0 THEN
        RAISE EXCEPTION 'future_days must be >= 0';
    END IF;
    start_day := current_date - retention_days;
    end_day := current_date + future_days;
    d := start_day;
    WHILE d <= end_day LOOP
        PERFORM guard_ensure_audit_partition(d);
        PERFORM guard_ensure_schedule_partition(d);
        d := d + 1;
    END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION guard_drop_old_partitions(retention_days int DEFAULT 30)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    cutoff date := current_date - retention_days;
    r record;
    dropped int := 0;
    part_day date;
BEGIN
    IF retention_days < 1 THEN
        RAISE EXCEPTION 'retention_days must be >= 1';
    END IF;

    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'audit'
          AND c.relname ~ '^audit_[0-9]{8}$'
    LOOP
        part_day := to_date(substring(r.part_name from '([0-9]{8})$'), 'YYYYMMDD');
        IF part_day < cutoff THEN
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'schedule'
          AND c.relname ~ '^schedule_[0-9]{8}$'
    LOOP
        part_day := to_date(substring(r.part_name from '([0-9]{8})$'), 'YYYYMMDD');
        IF part_day < cutoff THEN
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    RETURN dropped;
END;
$$;

CREATE OR REPLACE FUNCTION guard_retention_maintain(
    retention_days int DEFAULT 30,
    future_days int DEFAULT 7
)
RETURNS integer
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM guard_ensure_partitions(retention_days, future_days);
    RETURN guard_drop_old_partitions(retention_days);
END;
$$;

SELECT guard_retention_maintain(30, 7);

-- Optional: daily job when pg_cron is enabled (Neon: enable in project settings).
DO $cron$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron')
       AND NOT EXISTS (
           SELECT 1 FROM cron.job WHERE jobname = 'guard-retention-maintain'
       ) THEN
        PERFORM cron.schedule(
            'guard-retention-maintain',
            '15 3 * * *',
            $$SELECT guard_retention_maintain(30, 7)$$
        );
    END IF;
EXCEPTION
    WHEN undefined_table OR undefined_function THEN
        NULL;
END;
$cron$;
