-- 40-day range partitions; retain at least 30 calendar days (worst case ~two blocks ≈ 30–80 days).
-- Drop whole blocks with DROP TABLE when the entire block is outside retention.

CREATE OR REPLACE FUNCTION guard_partition_anchor()
RETURNS date
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT '2000-01-01'::date $$;

CREATE OR REPLACE FUNCTION guard_partition_days()
RETURNS integer
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT 40 $$;

CREATE OR REPLACE FUNCTION guard_partition_block_start(p_day date)
RETURNS date
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT guard_partition_anchor()
        + (
            (p_day - guard_partition_anchor())
            / guard_partition_days()
        ) * guard_partition_days();
$$;

CREATE OR REPLACE FUNCTION guard_partition_block_end(p_block_start date)
RETURNS date
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT p_block_start + guard_partition_days() $$;

-- ---------------------------------------------------------------------------
-- Rebuild audit + schedule (daily child partitions -> 40-day blocks)
-- ---------------------------------------------------------------------------
CREATE TABLE audit_retention_staging AS
SELECT id, ts, key, new_cfg, request_id, actor
FROM audit;

CREATE TABLE schedule_retention_staging AS
SELECT ts_date, plan, applied_at, applied_from_slot
FROM schedule;

DROP TABLE audit CASCADE;
DROP TABLE schedule CASCADE;

DROP FUNCTION IF EXISTS guard_ensure_audit_partition(date);
DROP FUNCTION IF EXISTS guard_ensure_schedule_partition(date);

CREATE TABLE audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    key TEXT NOT NULL,
    new_cfg JSONB NOT NULL,
    request_id UUID NULL,
    actor TEXT NULL,
    PRIMARY KEY (ts, id)
) PARTITION BY RANGE (ts);

CREATE INDEX IF NOT EXISTS audit_key_idx ON audit (key);

CREATE TABLE schedule (
    ts_date DATE NOT NULL,
    plan JSONB NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_from_slot TEXT NULL,
    PRIMARY KEY (ts_date)
) PARTITION BY RANGE (ts_date);

CREATE INDEX IF NOT EXISTS schedule_applied_at_idx ON schedule (applied_at DESC);

CREATE OR REPLACE FUNCTION guard_ensure_audit_block(p_block_start date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'audit_b' || to_char(p_block_start, 'YYYYMMDD');
    range_from timestamptz := p_block_start::timestamptz;
    range_to timestamptz := guard_partition_block_end(p_block_start)::timestamptz;
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF audit FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

CREATE OR REPLACE FUNCTION guard_ensure_schedule_block(p_block_start date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    part_name text := 'schedule_b' || to_char(p_block_start, 'YYYYMMDD');
    range_from date := p_block_start;
    range_to date := guard_partition_block_end(p_block_start);
BEGIN
    IF to_regclass('public.' || part_name) IS NOT NULL THEN
        RETURN;
    END IF;
    EXECUTE format(
        'CREATE TABLE %I PARTITION OF schedule FOR VALUES FROM (%L) TO (%L)',
        part_name, range_from, range_to
    );
END;
$$;

CREATE OR REPLACE FUNCTION guard_ensure_partitions(
    retention_days int DEFAULT 30,
    future_days int DEFAULT 7
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    oldest_keep date;
    last_needed date;
    block_start date;
    step int := guard_partition_days();
BEGIN
    IF retention_days < 1 THEN
        RAISE EXCEPTION 'retention_days must be >= 1';
    END IF;
    IF future_days < 0 THEN
        RAISE EXCEPTION 'future_days must be >= 0';
    END IF;

    oldest_keep := current_date - retention_days + 1;
    last_needed := current_date + future_days;
    block_start := guard_partition_block_start(oldest_keep);

    WHILE block_start <= guard_partition_block_start(last_needed) LOOP
        PERFORM guard_ensure_audit_block(block_start);
        PERFORM guard_ensure_schedule_block(block_start);
        block_start := block_start + step;
    END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION guard_drop_old_partitions(retention_days int DEFAULT 30)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    oldest_keep date;
    block_days int := guard_partition_days();
    r record;
    dropped int := 0;
    block_start date;
    block_end date;
BEGIN
    IF retention_days < 1 THEN
        RAISE EXCEPTION 'retention_days must be >= 1';
    END IF;

    oldest_keep := current_date - retention_days + 1;

    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'audit'
          AND c.relname ~ '^audit_b[0-9]{8}$'
    LOOP
        block_start := to_date(substring(r.part_name from 'b([0-9]{8})$'), 'YYYYMMDD');
        block_end := block_start + block_days;
        IF block_end <= oldest_keep THEN
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'schedule'
          AND c.relname ~ '^schedule_b[0-9]{8}$'
    LOOP
        block_start := to_date(substring(r.part_name from 'b([0-9]{8})$'), 'YYYYMMDD');
        block_end := block_start + block_days;
        IF block_end <= oldest_keep THEN
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    RETURN dropped;
END;
$$;

CREATE OR REPLACE FUNCTION guard_retention_maintain(
    retention_days int DEFAULT 30,
    future_days int DEFAULT 7
)
RETURNS integer
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM guard_ensure_partitions(retention_days, future_days);
    RETURN guard_drop_old_partitions(retention_days);
END;
$$;

DO $migrate_data$
DECLARE
    min_day date;
    max_day date;
    block_start date;
    step int := guard_partition_days();
BEGIN
    SELECT
        coalesce(min(ts::date), current_date),
        coalesce(max(ts::date), current_date)
    INTO min_day, max_day
    FROM audit_retention_staging;

    block_start := guard_partition_block_start(min_day);
    WHILE block_start <= guard_partition_block_start(max_day) LOOP
        PERFORM guard_ensure_audit_block(block_start);
        block_start := block_start + step;
    END LOOP;

    SELECT
        coalesce(min(ts_date), current_date),
        coalesce(max(ts_date), current_date)
    INTO min_day, max_day
    FROM schedule_retention_staging;

    block_start := guard_partition_block_start(min_day);
    WHILE block_start <= guard_partition_block_start(max_day) LOOP
        PERFORM guard_ensure_schedule_block(block_start);
        block_start := block_start + step;
    END LOOP;
END;
$migrate_data$;

INSERT INTO audit (id, ts, key, new_cfg, request_id, actor)
SELECT id, ts, key, new_cfg, request_id, actor
FROM audit_retention_staging;

INSERT INTO schedule (ts_date, plan, applied_at, applied_from_slot)
SELECT ts_date, plan, applied_at, applied_from_slot
FROM schedule_retention_staging;

DROP TABLE audit_retention_staging;
DROP TABLE schedule_retention_staging;

SELECT guard_retention_maintain(30, 7);
